services:
    wolnut:
        image: hardwarehaven/wolnut:latest
        # build: .
        container_name: wolnut
        network_mode: host
        restart: unless-stopped
        volumes:
            - ./config.yaml:/config/config.yaml