name: ğŸ“ Publish PR Results
on:
  workflow_run:
    workflows: ["ğŸ Test application code"]
    types:
      - completed

permissions:
  checks: write
  pull-requests: write

jobs:
  publish-test-report:
    name: Publish Test Report
    runs-on: ubuntu-latest
    # Only run on pull request triggered workflows
    if: github.event.workflow_run.event == 'pull_request' && github.actor != 'dependabot[bot]'
    steps:
      - name: Download all test reports
        uses: actions/download-artifact@v4
        with:
          path: test-results
          pattern: pytest-results-*

      - name: Publish Test Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          files: "test-results/**/*.xml"
          comment_mode: off

  comment-on-success:
    name: Add Report Link to PR
    runs-on: ubuntu-latest
    # Only run on successful pull request workflows that have an associated PR
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.pull_requests

    steps:
      - name: Create PR comment with link to workflow run
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ github.event.workflow_run.pull_requests[0].number }}
          header: test-report-link
          message: |
            ğŸ“Š Test and coverage reports are available in the [workflow run summary](${{ github.event.workflow_run.html_url }}).

            Click "Summary" on the left of the workflow run page to see the full report.